### ISSUE TITLE
Таблица power_quality

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_energymanagement#12]
1)Подсветка строк. 
Каждая строка подсвечивается следующими цветами:
>0, <1.1 = зеленый
>=1.1, <2 = желтый
>=2, красный
Значения, по которым работает подсветка — колонка index

2)Убрать паджинацию

3)Сделать третью колонку такого вида, объединяющую все строки, вычислять ее значение как максимальный index в таблице. Подсветка по тем же правилам, но считается из значения этой колонки. См. пример: 
![image](https://user-images.githubusercontent.com/3315944/44173053-8986c300-a0e7-11e8-930f-fa038ffc9fcf.png)

**Comment by nismangulov** [comment]
@vvzvlad 

Обновил табличку: убрал пагинацию, добавил подсветку строк и последний столбец с максимальным значением (тоже с подсветкой). Залил в #15

**Comment by vvzvlad** [comment]
работает
