### ISSUE TITLE
Страница electrical_shields

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_energymanagement#13]
Сделать 4 карточки(как на дашборде), на каждой из которых расположить следующую информацию:

Max current: 60A
Current: 20A
Max temperature: 50°C
Current temperature: 37°C

**Comment by nismangulov** [comment]
@vvzvlad 

Обновил страничку с информацией об электрощитах. Добавил 4 карточки с инфой, как ты описал, залил в #16

**Comment by vvzvlad** [comment]
работает
