### ISSUE TITLE
Вертикальная линия в таблице power_quality

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_energymanagement#19]
![image](https://user-images.githubusercontent.com/3315944/44214260-68ba7e00-a178-11e8-946f-c04379f339d2.png)
Колонка max должна быть отделена от остальной таблицы вертикальной линией.

**Comment by nismangulov** [comment]
@vvzvlad 

Добавил вертикальную линию. Ещё поправил белую полосу под последней строкой таблицы - она резала глаз, убрать её совсем не удалось, поэтому сделал её того же цвета, как и все бордеры в таблице.

**Comment by vvzvlad** [comment]
Да, хорошо, спасибо
