### ISSUE TITLE
Выровнять надпись "Powered by IMPACT"

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_energymanagement#20]
Наверное, стоит сделать все надписи на одном уровне:
![image](https://user-images.githubusercontent.com/3315944/44222080-1edb9300-a18c-11e8-9ddc-ae84bef4d821.png)

**Comment by nismangulov** [comment]
@vvzvlad 

Переработал центрирование в хедере - теперь оно работает нормально вне зависимости от высоты хедера. Залил в #22

**Comment by vvzvlad** [comment]
![image](https://user-images.githubusercontent.com/3315944/44251307-90edbf80-a200-11e8-82d7-5830dc9861f8.png)
Теперь эта надпись не по середине. Или выровнять по нижнему краю, или все по центру.

**Comment by nismangulov** [comment]
@vvzvlad 

Поправил выравнивание всех надписей по линеечке, должно теперь стать лучше.  Если не ок - давай действительно сдвинем вниз. Залил в #24
