### ISSUE TITLE
Уменьшить рамки вокруг страниц

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_energymanagement#4]
Слишком много пустого пространства вокруг страниц, надо сделать как в glue_panel
![image](https://user-images.githubusercontent.com/3315944/44080302-4f8c7516-9fb4-11e8-8377-024c71102017.png)
![image](https://user-images.githubusercontent.com/3315944/44080309-5364f834-9fb4-11e8-9ffc-4d18abdece75.png)

**Comment by nismangulov** [comment]
@vvzvlad 

Уменьшил отступы, уменьшил размер свернутого бокового и верхнего меню. Залил в #9

**Comment by vvzvlad** [comment]
работает
