### ISSUE TITLE
Три диаграммы в карточке Phase current balance

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_energymanagement#5]
Диаграммы типа "пончик без куска", см. пример:
![image](https://user-images.githubusercontent.com/3315944/44107181-2a932822-9fff-11e8-816d-cedfb0414630.png)

Диапазон тот же, что на картинке.

**Comment by nismangulov** [comment]
@vvzvlad 

А можешь дать ссылку на референс? Может получится оттуда что-нибудь полезное получить.

**Comment by vvzvlad** [comment]
Это стандартный график из grafana. У нас ее в общем доступе нет, так просто дать ссылку не могу. Это режим отображения singlestat-Options-Gauge

**Comment by vvzvlad** [comment]
Сделай пока три вертикальных полоски, меняющих цвет(150-207 желтый, 208-252 зеленый, 253-300 красный) со значением напряжения внизу. Подписи полосок: L1, L2, L3. 
Красиво потом сделаем.

**Comment by nismangulov** [comment]
@vvzvlad 

Сделал простой вертикальный чарт, сделал в нем смену цвета в зависимости от значения, передающегося в компонент. Добавил три таких на страничку "Phase current balance", по одному на каждую фазу. Залил в #18. Выглядят они вот так:

![image](https://user-images.githubusercontent.com/6184888/44194996-89bfa680-a159-11e8-9755-ab2079a1aac0.png)

**Comment by vvzvlad** [comment]
Давай со 150, да. 
А на самой карточке сделаешь?

**Comment by nismangulov** [comment]
@vvzvlad 

> Давай со 150, да.
Сделал график со 150V.

> А на самой карточке сделаешь?

Сделал в карточке на дашборде полупрозрачные графики, как мы делали с bar chart. Выглядят вот так, ещё можно лейблы с напряжением прятать, если они не нужны

![image](https://user-images.githubusercontent.com/6184888/44247984-ce0a7f80-a209-11e8-8726-8c11e0e204d8.png)

Залил все в #23

**Comment by vvzvlad** [comment]
Лейблы пусть будут. Я убрал прозрачность, пусть это будет основная информация на карточке. 
1)Перенести напряжения вбок(т.е. текущее напряжение — это иконка с численным значением, указывающая на текущий уровень, плавающая вместе с уровнем напряжения)
2)Сделать в таком же виде максимальные, минимальные значения, и пределы(150-207-253-300)
3)Снизу подписать: L1, L2, L3

**Comment by nismangulov** [comment]
@vvzvlad 

Сделал все три пункта, залил в #25.

Текущее значение решил разместить слева, а все пределы - справа, чтобы они не накладывались друг на друга. Ещё пришлось пределы выделить цветом - чтобы колонки явнее выделялись. Если все цифры делать чёрными - всё сливается и путается.

![image](https://user-images.githubusercontent.com/6184888/44382487-e2ff4f80-a536-11e8-9640-9a49bd9f3bbe.png)
