### ISSUE TITLE
Таблица на странице power_quality

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_energymanagement#6]
Сделать на странице power_quality таблицу.
Колонки: Parameter, Value, Index
Строки: 
Power factor index, 1.2, 1.2
Total harmonic distortion index, 1.7, 1.7
Frequency deviation index, 1.2, 1.2
Voltage deviation index, 1.1, 1.1
Phase imbalance index, 1, 1

**Comment by nismangulov** [comment]
@vvzvlad 

Добавил стандартную табличку с этими данными в #10, особых настроек к ней пока не применял.

**Comment by vvzvlad** [comment]
работает
